// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;
using Controllers;

[TestFixture]
public class EventControllerTests {

  [Test]
  public void TestFrameworkIsHere() {
    Assert.IsTrue(new EventController() != null);
    Assert.IsFalse(false);
  }

  [Test]
  public void MultipleTests(){
    Assert.IsTrue(true);
  }

  [Test]
  public void TestExternalAssembly(){
    var c = new Controller();
    Assert.IsNotNull(c);
  }

}